# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a163ee4250f1e5df3c20f9c127b7403ad7f389947577a1229b40775abcf3a7c07170277ea79c55eeb4f25c29feecd8521b52ff98e4b68977ef3f8a61aab0d3

test:
  secret_key_base: cdb61bb46039243e565cf5b3815a61340b66e144a753072eadf72bf33a8924be41f1293ce922abf03016bbc1283138a8e580925267cf2a74bcde325b9c05edc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
